### ISSUE TITLE
Client connection fails

### ISSUE THREAD

**Issue by zeya2u9** [doudoulong/Minecruft-PT#2]
I was trying out Minecruft-PT on Ubuntu-20.04 (for both client and server).
I am able to build these dockers --> mserver, testproxy and socks on server -side. All are up and running.
But while running the `$ sudo docker-compose -f iperf-test.yml up --build testclient` command on client-side, it throws an error at client side and shows that Bot has left the game on server side. 

**Server Side:**
![server_side](https://user-images.githubusercontent.com/12155370/206201050-65a662cc-b7b9-4af3-9a74-ace9dc55fc42.png)

**Client Side:**
![client_side](https://user-images.githubusercontent.com/12155370/206231487-e86ef321-a875-4aa8-b014-3e0b8254e2a3.jpg)

Can you take a look and see what could be the problem?
Thanks

**Comment by beerpromax** [comment]
It's a library version problem. It is now fixed. Please use the latest version.
I'm closing this issue.
